# Topic Modeling

## Introduction

Another popular text analysis technique is called topic modeling. The ultimate goal of topic modeling is to find various topics that are present in your corpus. Each document in the corpus will be made up of at least one topic, if not multiple topics.

In this notebook, we will be covering the steps on how to do **Latent Dirichlet Allocation (LDA)**, which is one of many topic modeling techniques. It was specifically designed for text data.

To use a topic modeling technique, you need to provide (1) a document-term matrix and (2) the number of topics you would like the algorithm to pick up.

Once the topic modeling technique is applied, your job as a human is to interpret the results and see if the mix of words in each topic make sense. If they don't make sense, you can try changing up the number of topics, the terms in the document-term matrix, model parameters, or even try a different model.

## Topic Modeling - Attempt #1 (All Text)

In [53]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,abandon,abandoned,abandoning,abate,abduct,abilities,ability,able,abolishing,aboveaverage,...,younger,youngest,yourewell,youve,youyou,yunkai,zealot,zo,zuriff,Ä“za
speaker,,,,,,,,,,,,,,,,,,,,,
tyrion,1,2,0,0,1,1,0,6,2,1,...,1,2,0,27,0,2,0,0,0,0
cersei,1,1,0,0,0,0,0,0,0,0,...,0,1,0,15,0,0,0,0,0,0
jaime,2,0,1,0,0,0,0,5,0,0,...,0,0,0,9,1,0,0,0,0,0
daenerys,0,2,0,0,0,0,0,3,0,0,...,0,0,0,3,0,8,0,3,0,1
jon,1,0,0,0,0,0,0,0,0,0,...,0,0,1,6,0,0,0,0,0,0
sansa,2,0,3,0,0,0,0,2,0,0,...,1,0,0,6,0,0,0,0,2,0
davos,1,0,0,0,0,0,1,0,0,0,...,0,0,0,2,0,0,0,0,0,0
varys,1,2,0,0,0,0,0,2,0,0,...,0,0,0,4,0,2,0,0,0,0
arya,0,0,0,0,0,0,0,1,0,0,...,2,1,0,5,0,0,0,0,0,0
tywin,1,0,0,1,0,0,0,2,0,0,...,0,0,0,7,0,0,0,0,0,0
theon,1,0,0,0,0,0,0,0,0,0,...,0,0,0,4,0,0,0,0,0,0
sam,0,1,0,0,0,0,0,1,0,0,...,0,1,0,1,0,0,0,0,0,0
bronn,0,0,0,0,0,0,0,0,0,0,...,0,1,0,3,0,0,0,0,0,0
brienne,1,0,0,0,0,0,0,1,0,0,...,0,0,0,3,0,0,0,0,0,0
olenna,0,1,0,0,0,0,0,2,0,0,...,0,0,0,2,0,0,1,0,0,0

In [54]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [55]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

speaker,tyrion,cersei,jaime,daenerys,jon,sansa,davos,varys,arya,tywin,theon,sam,bronn,brienne,olenna
abandon,1,1,2,0,1,2,1,1,0,1,1,0,0,1,0
abandoned,2,1,0,2,0,0,0,2,0,0,0,1,0,0,1
abandoning,0,0,1,0,0,3,0,0,0,0,0,0,0,0,0
abate,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
abduct,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [56]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [57]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [58]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.005*"people" + 0.005*"just" + 0.005*"hes" + 0.005*"queen" + 0.004*"north" + 0.004*"make" + 0.004*"time" + 0.004*"tell" + 0.004*"going" + 0.004*"kill"'),
 (1,
  '0.005*"yes" + 0.004*"time" + 0.004*"going" + 0.004*"lady" + 0.004*"people" + 0.004*"oh" + 0.004*"queen" + 0.004*"just" + 0.003*"tell" + 0.003*"say"')]

In [59]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.006*"people" + 0.004*"brother" + 0.004*"oh" + 0.004*"queen" + 0.004*"kill" + 0.004*"jon" + 0.004*"dragons" + 0.004*"yes" + 0.004*"going" + 0.003*"didnt"'),
 (1,
  '0.005*"people" + 0.005*"just" + 0.005*"time" + 0.004*"queen" + 0.004*"yes" + 0.004*"going" + 0.004*"tell" + 0.004*"stark" + 0.004*"make" + 0.004*"lady"'),
 (2,
  '0.009*"grace" + 0.006*"north" + 0.005*"watch" + 0.005*"wall" + 0.005*"army" + 0.005*"fight" + 0.005*"people" + 0.004*"time" + 0.004*"night" + 0.004*"just"')]

In [60]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.001*"time" + 0.001*"yes" + 0.001*"tell" + 0.001*"just" + 0.000*"people" + 0.000*"hes" + 0.000*"make" + 0.000*"going" + 0.000*"queen" + 0.000*"kill"'),
 (1,
  '0.000*"just" + 0.000*"people" + 0.000*"tell" + 0.000*"kill" + 0.000*"ive" + 0.000*"time" + 0.000*"queen" + 0.000*"let" + 0.000*"yes" + 0.000*"going"'),
 (2,
  '0.005*"people" + 0.005*"time" + 0.004*"just" + 0.004*"hes" + 0.004*"ive" + 0.004*"ser" + 0.004*"dead" + 0.004*"grace" + 0.004*"going" + 0.004*"fight"'),
 (3,
  '0.005*"people" + 0.005*"queen" + 0.005*"just" + 0.005*"tell" + 0.005*"yes" + 0.005*"going" + 0.004*"make" + 0.004*"time" + 0.004*"say" + 0.004*"stark"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [61]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [62]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('corpus.pkl')
data_clean

      speaker                                         transcript
855    tyrion   your grace i know my brother he came here alo...
117    cersei   your mother might have prepared you you flowe...
341     jaime   she did she lied to me as well she never had ...
156  daenerys   who stabbed him in the back and cut his throa...
358       jon   we need every man we can get i thought wed lo...
746     sansa   youre right we cant trust him he attacked my ...
176     davos   you are now look i made it through most of my...
884     varys   oh lord tyrion come in come in oh always in c...
29       arya   you make my weapon yet you should make mine f...
866     tywin   wolfsbane a rare substance this is no common ...
833     theon   my queen she only has a few ships and she cou...
736       sam   im sorry hes beautiful hes beautiful  does he...
90      bronn   to the boys drunk lannisters thank you very m...
86    brienne   you dont know me well your grace but i know s...
617    olenna    there appears to be a good deal of room else...

In [63]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns['speaker'] = data_clean['speaker']
data_nouns

                                            transcript   speaker
855  grace i brother truth i fool i masses shes tim...    tyrion
117  mother way wait child youre woman idea prospec...    cersei
341  intention army north greyjoys fleet troops com...     jaime
156  back throat iron throne blood floor stories th...  daenerys
358  man umbers fight night command chance crypt th...       jon
746  father streets house family trust life yours p...     sansa
176  i years fight battle bastards walls i theyll o...     davos
884  lord tyrion come confidence time life proof tr...     varys
29   weapon mine crypt youre fighter youve apprenti...      arya
866  wolfsbane substance assassin i care man name i...     tywin
833  queen ships sailing iron name i winterfell lad...     theon
736  im sorry hes hes beautiful name crasters daugh...       sam
90   boys lannisters time i mam iron poker brother ...     bronn
86   grace i ser jaime man honor i captor prisoner ...   brienne
617  deal room premises everyone rest seats grace y...    olenna

In [64]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns['speaker']
data_dtmn

,abilities,ability,absence,absolution,abuses,accent,accents,access,accident,accommodations,...,yoren,yorens,youd,youll,youve,yunkai,zealot,zo,zuriff,Ä“za
speaker,,,,,,,,,,,,,,,,,,,,,
tyrion,1,0,2,0,0,0,0,0,0,0,...,0,0,4,8,11,2,0,0,0,0
cersei,0,0,0,1,1,0,0,0,2,1,...,0,0,3,6,5,0,0,0,0,0
jaime,0,0,0,0,0,1,0,0,2,0,...,0,0,3,7,2,0,0,0,0,0
daenerys,0,0,0,0,0,0,0,0,0,0,...,0,0,4,6,1,4,0,3,0,1
jon,0,0,0,0,0,0,0,0,0,0,...,0,0,1,2,0,0,0,0,0,0
sansa,0,0,0,0,0,0,0,0,0,0,...,0,0,1,4,4,0,0,0,2,0
davos,0,1,0,0,0,2,0,0,0,0,...,0,0,1,5,2,0,0,0,0,0
varys,0,0,1,0,0,1,1,0,0,0,...,0,0,0,2,1,2,0,0,0,0
arya,0,0,0,0,0,0,0,0,0,0,...,1,1,1,2,3,0,0,0,0,0
tywin,0,0,0,0,0,0,0,0,0,1,...,0,0,1,5,1,0,0,0,0,0
theon,0,0,1,0,0,0,0,0,0,0,...,0,0,0,3,1,0,0,0,0,0
sam,0,0,0,0,0,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
bronn,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
brienne,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
olenna,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0

In [65]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [66]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.011*"man" + 0.010*"king" + 0.009*"father" + 0.008*"men" + 0.008*"lord" + 0.008*"way" + 0.007*"brother" + 0.007*"grace" + 0.006*"son" + 0.005*"war"'),
 (1,
  '0.014*"men" + 0.012*"father" + 0.011*"man" + 0.011*"lord" + 0.008*"king" + 0.006*"city" + 0.006*"grace" + 0.006*"world" + 0.006*"army" + 0.006*"brother"')]

In [67]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.012*"lord" + 0.012*"man" + 0.010*"father" + 0.009*"men" + 0.008*"way" + 0.007*"brother" + 0.007*"king" + 0.007*"mother" + 0.006*"family" + 0.006*"things"'),
 (1,
  '0.012*"man" + 0.012*"men" + 0.011*"father" + 0.010*"king" + 0.008*"lord" + 0.007*"world" + 0.006*"brother" + 0.006*"grace" + 0.006*"kings" + 0.006*"way"'),
 (2,
  '0.016*"men" + 0.014*"wall" + 0.011*"army" + 0.009*"father" + 0.009*"grace" + 0.009*"night" + 0.008*"nights" + 0.008*"north" + 0.008*"wildlings" + 0.007*"watch"')]

In [68]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.001*"men" + 0.001*"man" + 0.001*"father" + 0.001*"king" + 0.001*"lord" + 0.001*"grace" + 0.001*"way" + 0.001*"war" + 0.001*"army" + 0.001*"stark"'),
 (1,
  '0.017*"men" + 0.012*"father" + 0.011*"lord" + 0.011*"man" + 0.008*"brother" + 0.007*"army" + 0.007*"jon" + 0.006*"hes" + 0.006*"way" + 0.006*"king"'),
 (2,
  '0.013*"man" + 0.011*"father" + 0.011*"lord" + 0.009*"men" + 0.007*"way" + 0.007*"king" + 0.006*"stark" + 0.005*"life" + 0.005*"hand" + 0.005*"city"'),
 (3,
  '0.011*"man" + 0.011*"king" + 0.010*"father" + 0.009*"men" + 0.008*"grace" + 0.008*"lord" + 0.007*"brother" + 0.007*"kings" + 0.007*"way" + 0.007*"world"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [69]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [70]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj['speaker'] = data_clean['speaker']
data_nouns_adj

                                            transcript   speaker
855  grace i brother full hed truth i fool i masses...    tyrion
117  mother dear way wait child youre woman idea pr...    cersei
341  intention army north greyjoys fleet fresh troo...     jaime
156  back throat iron throne blood floor other stor...  daenerys
358  man i other umbers straight fight night comman...       jon
746  right trust father streets house family same v...     sansa
176  i most years fight battle bastards right walls...     davos
884  lord tyrion come oh confidence wonderful time ...     varys
29   weapon mine first sure stronger crypt youre fi...      arya
866  wolfsbane rare substance common assassin i car...     tywin
833  queen few ships shes sailing iron name i winte...     theon
736  im sorry hes beautiful hes beautiful name i cr...       sam
90   boys lannisters first time i mam iron poker li...     bronn
86   grace i ser jaime man honor i captor prisoner ...   brienne
617  good deal room premises everyone rest superior...    olenna

In [71]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj['speaker']
data_dtmna

,abilities,ability,able,aboveaverage,absence,absolution,abstract,absurd,abuses,accent,...,yoren,yorens,youd,younger,youngest,yunkai,zealot,zo,zuriff,Ä“za
speaker,,,,,,,,,,,,,,,,,,,,,
tyrion,1,0,6,1,2,0,1,0,0,0,...,0,0,7,1,2,2,0,0,0,0
cersei,0,0,0,0,0,1,0,0,1,0,...,0,0,3,0,1,0,0,0,0,0
jaime,0,0,5,0,0,0,0,0,0,1,...,0,0,6,0,0,0,0,0,0,0
daenerys,0,0,3,0,0,0,0,0,0,0,...,0,0,4,0,0,4,0,3,0,1
jon,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
sansa,0,0,2,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,2,0
davos,0,1,0,0,0,0,0,0,0,2,...,0,0,1,0,0,0,0,0,0,0
varys,0,0,2,0,1,0,0,0,0,1,...,0,0,0,0,0,2,0,0,0,0
arya,0,0,1,0,0,0,0,0,0,0,...,1,1,2,2,1,0,0,0,0,0
tywin,0,0,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
theon,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
sam,0,0,1,0,0,0,0,0,0,0,...,0,0,3,0,1,0,0,0,0,0
bronn,0,0,0,0,0,0,0,0,0,1,...,0,0,3,0,1,0,0,0,0,0
brienne,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
olenna,0,0,2,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [72]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [73]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"lannister" + 0.005*"cersei" + 0.004*"joffrey" + 0.004*"stannis" + 0.004*"jon" + 0.004*"sansa" + 0.003*"children" + 0.003*"sword" + 0.003*"jaime" + 0.003*"dragons"'),
 (1,
  '0.006*"children" + 0.005*"dragons" + 0.004*"jon" + 0.004*"enemies" + 0.004*"free" + 0.004*"high" + 0.003*"daughter" + 0.003*"nights" + 0.003*"friend" + 0.003*"wildlings"')]

In [74]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.008*"jon" + 0.005*"castle" + 0.005*"stannis" + 0.004*"sword" + 0.004*"nights" + 0.004*"joffrey" + 0.004*"commander" + 0.004*"wildlings" + 0.004*"black" + 0.004*"boys"'),
 (1,
  '0.006*"dragons" + 0.006*"children" + 0.005*"lannister" + 0.004*"tyrion" + 0.004*"enemies" + 0.004*"daughter" + 0.004*"joffrey" + 0.004*"high" + 0.004*"cersei" + 0.003*"red"'),
 (2,
  '0.005*"cersei" + 0.004*"children" + 0.004*"lannister" + 0.004*"westeros" + 0.004*"dragons" + 0.004*"jaime" + 0.003*"sansa" + 0.003*"rock" + 0.003*"joffrey" + 0.003*"daenerys"')]

In [75]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"sword" + 0.005*"dragons" + 0.005*"stannis" + 0.005*"children" + 0.005*"cersei" + 0.005*"lannister" + 0.004*"jon" + 0.004*"free" + 0.004*"castle" + 0.004*"nights"'),
 (1,
  '0.010*"jon" + 0.009*"reek" + 0.006*"castle" + 0.006*"maester" + 0.005*"commander" + 0.005*"theon" + 0.005*"white" + 0.004*"greyjoy" + 0.004*"wildlings" + 0.004*"black"'),
 (2,
  '0.006*"daughter" + 0.006*"high" + 0.005*"lannister" + 0.005*"joffrey" + 0.005*"tyrell" + 0.005*"tyrion" + 0.004*"children" + 0.004*"jaime" + 0.004*"dragons" + 0.003*"strong"'),
 (3,
  '0.006*"jon" + 0.005*"cersei" + 0.005*"joffrey" + 0.004*"westeros" + 0.004*"dragons" + 0.004*"lannister" + 0.004*"children" + 0.004*"sansa" + 0.004*"happy" + 0.003*"friends"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [76]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.008*"daughter" + 0.007*"high" + 0.006*"joffrey" + 0.005*"tyrell" + 0.005*"jaime" + 0.004*"children" + 0.004*"red" + 0.004*"lannister" + 0.004*"sparrow" + 0.003*"loras"'),
 (1,
  '0.007*"lannister" + 0.005*"castle" + 0.005*"sansa" + 0.005*"tyrion" + 0.004*"jaime" + 0.004*"sword" + 0.004*"reek" + 0.004*"starks" + 0.003*"boys" + 0.003*"honor"'),
 (2,
  '0.009*"joffrey" + 0.007*"cersei" + 0.006*"sword" + 0.005*"arya" + 0.005*"oysters" + 0.004*"hound" + 0.004*"clams" + 0.004*"god" + 0.004*"jon" + 0.004*"pie"'),
 (3,
  '0.007*"jon" + 0.006*"dragons" + 0.006*"children" + 0.004*"stannis" + 0.004*"cersei" + 0.004*"westeros" + 0.004*"daenerys" + 0.004*"watch" + 0.004*"commander" + 0.003*"free"')]

These four topics look pretty decent. Let's settle on these for now.

In [77]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a[0][0] for a in corpus_transformed], data_dtmna.index))

[(3, 'tyrion'),
 (0, 'cersei'),
 (1, 'jaime'),
 (3, 'daenerys'),
 (3, 'jon'),
 (3, 'sansa'),
 (3, 'davos'),
 (3, 'varys'),
 (2, 'arya'),
 (1, 'tywin'),
 (1, 'theon'),
 (3, 'sam'),
 (1, 'bronn'),
 (1, 'brienne'),
 (0, 'olenna')]

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: [Brienne]
* Topic 1: [Sansa, Davos]
* Topic 2: [Sam, Jon, Theon]
* Topic 3: [Tyrion, Cersei, Jaime, Daenerys, Varys, Arya, Tywin, Bronn, Olenna]